services:
  - type: web
    name: connect4-ai
    env: python
    buildCommand: |
      # 1) Cài Rust toolchain
      curl -sSf https://sh.rustup.rs | sh -s -- -y
      export PATH="$HOME/.cargo/bin:$PATH"

      # 2) Cài thư viện C cần thiết cho maturin/PyO3
      apt-get update && \
      apt-get install -y --no-install-recommends \
        build-essential pkg-config libssl-dev clang && \
      rm -rf /var/lib/apt/lists/*

      # 3) Nâng cấp pip, cài maturin
      pip install -U pip
      pip install "maturin>=1,<2"

      # 4) Cài PyTorch (chọn CPU-only hoặc CUDA)
      # CPU-only:
      pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu

      # 5) Cài package của bạn (sẽ compile Rust extension)
      pip install -e .

    startCommand: python src/c4a0/main.py

    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: PYTORCH_CUDA_ALLOC_CONF
        value: "max_split_size_mb:128"
